export const FETCH_USER_LIST = 'FETCH_USER_LIST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';



export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';


export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';

export const DELETE_USER_LIST = 'DELETE_USER_LIST';

export const SEARCH_DATA_LIST = 'SEARCH_DATA_LIST';
export const SEARCH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS';
export const SEARCH_DATA_FAILURE = 'SEARCH_DATA_FAILURE';
